### ISSUE TITLE
Unable to mute Revendreth flight masters

### ISSUE THREAD

**Issue by ZehelFenris** [funkydude/MuteSoundFile#19]
says "There is no sound with id '159123' or you have sound disabled" when i try to add it to mute list but when i use "/script PlaySound(159123)" it plays the sound just fine which it also do when i talk to the flight masters so im sure the sound arent muted

**Comment by funkydude** [comment]
PlaySound doesn't play a sound file, it plays a sound kit. A sound kit can be multiple sounds together. Perhaps you already noticed this, because running that code will swap between the 2 speech lines. Please use the preview functionality of this addon to test if a sound **file** is correct.

I did a search on wow.tools and here and the results, maybe blocking these file id's will help:
![image](https://user-images.githubusercontent.com/16833/101231293-264b4100-36a2-11eb-9522-9df865a3e31b.png)

**Comment by ZehelFenris** [comment]
to be fair i had no clue there was a difference i thought it was all the same but thanks for the help :D

**Comment by funkydude** [comment]
No problem, it's an easy mistake to make. Did you also intend to mute the farewell sounds?

**Comment by ZehelFenris** [comment]
when i knew that it wasnt the right id i was using and how to find the right one i added the farewell and angry sound as well

**Comment by funkydude** [comment]
Angry sound? Is that when you click them too many times?

**Comment by ZehelFenris** [comment]
i believe so
