### ISSUE TITLE
[Feature Request] Upload the older versions as an archive

### ISSUE THREAD

**Issue by Pocokk** [funkydude/MuteSoundFile#42]
Dear funkydude,

I've just recently (re)found this great addon of yours and it works as flawlessly as I remembered, thank you for your continuous hard work on it!

However if I'm not mistaken, it had previous versions available for years (prior to BFA patch), I was wondering if you could reupload those earlier iterations to some place? Are they even available anymore locally on your PC as project files? Or I'm just misremembering it badly and it was actually a completely different (albeit functionally the same) addon that I was using years ago? 

Looking forward to your answer, thank you and best wishes,

Pocok

**Comment by AlexFolland** [comment]
What is the point of this?  Why not just clone the repo and checkout whichever commit you want?  This is GitHub, a hosting platform for git repositories.  Git is a version control system.  Its primary function is to track changes over time.

**Comment by Pocokk** [comment]
Apologize, I remember a version of this addon that existed 5-10 years ago, but the commits are only available since 2019. 

I can't clone non-existent info that weren't uploaded here, that's why I want to get ahold of those "older" versions. 

In case I'm mistaken and there wasn't a MuteSoundFile addon  back then (just something very similarly sounding), then I'm sorry for this confusion.

**Comment by funkydude** [comment]
The addon has only existed since the `MuteSoundFile` API was added to the game. Don't recall exactly when that was, think it was BfA, but they added it because they also purposely broke the ability for you to replace game sound files with custom ones.

Regardless, you can always go on curseforge and find years old versions of addons by just scrolling back the historic list of their versions. If it doesn't go as far back as you need it to, then the addon didn't exist at that point in time.

**Comment by AlexFolland** [comment]
@Pocokk You may be thinking of [MuteAnnoyingWoWSounds](https://www.curseforge.com/wow/addons/mute-wow-sounds) and/or [MuteAnnoying](https://www.curseforge.com/wow/addons/muteannoying).  Both still exist and are still able to be downloaded.  Both now use the `MuteSoundFile` function instead of directly overriding sound files in the WoW data directories with empty sound files.
